### ISSUE TITLE
[FEATURE]: 프로젝트 모듈화 세팅

### ISSUE THREAD

**Issue by J0onYEong** [3IDLES/idle-iOS#2]
### 진행할 작업

Tuist를 사용한 모듈화 작업을 위한 세팅입니다.

### Todo

- [x] 모듈 의존성 Swift 코드화
- [x] build configuration세팅
- [x] Scaffold를 사용한 Feature모듈 파일 자동 생성
- [x] Coordinator 및 DI 모듈 생성

### 기타사항

- Tuist 버전은 4.12.1 입니다.
- 모듈에 대한 정의는 [링크](https://grove-maraca-55d.notion.site/6d6ac086da3f44d6bac943e1d19b0c27?pvs=4)에 기록되어 있습니다. 
- 프로젝트는 모든 모듈은 워크스페이스를 통해 접근할 수 있습니다.
